### ISSUE TITLE
User is not deleted when Matrimony Profile is deleted.

### ISSUE THREAD

**Issue by bhawanabadlani** [jpsoffice/vmb#114]

**Comment by rtnpro** [comment]
This should be the other way round.

- When a user is deleted, the associated profile should be deleted.
   - We need to implement it as part of GDPR. We currently don't have a way to delete a user or deactivate a user account
- When a profile is created by admin, we should create a user for it, and send a password reset link to the user automatically.

cc @bhawanabadlani
